server:
  port: 8080
  compression:
    enable: true
    mime-types: text/html, text/xml, text/plain, application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4